### PR TITLE
added gs221 - risk of celiac and gluten intolerance, but also comment…

### PR DESCRIPTION
**Pull request by calweb**
…ed out gs216 due to the module not currently existing

I noticed the genoset test is missing for genoset-216 APOE, so i commented them out until the module exists?

### CODE REVIEW

**Comment by kevincol54** [comment]
Can you comment back in 216? I got it published on NPM 😄

**Comment by calweb** [comment]
cool, ill update the  pr

**Comment by calweb** [comment]
@kevincol54 should be good now

**Comment by kevincol54** [comment]
@calweb you da man! mergin like its tuesday at 9PM

**Pull request merged**
